import 'dart:convert';
import 'dart:typed_data';

import 'package:libsignal_protocol_dart/libsignal_protocol_dart.dart';

import 'e2ee_key_value_store.dart';

/// Persistent [SignalProtocolStore] implementation backed by an
/// [E2eeKeyValueStore].
///
/// Session records, prekeys, signed prekeys and trusted identities are stored
/// as serialized protobuf blobs (base64) so the underlying Signal ratchet state
/// survives app restarts.
class SecureSignalStore extends SignalProtocolStore {
  SecureSignalStore(this._store);

  final E2eeKeyValueStore _store;

  static const _identityKeyPairKey = 'identity_key_pair';
  static const _registrationIdKey = 'local_registration_id';

  String _sessionKey(SignalProtocolAddress address) =>
      'session:${address.getName()}:${address.getDeviceId()}';

  String _identityKeyKey(SignalProtocolAddress address) =>
      'trusted_identity:${address.getName()}';

  String _preKeyKey(int id) => 'prekey:$id';

  String _signedPreKeyKey(int id) => 'signed_prekey:$id';

  String _signedPreKeyIdsKey() => 'signed_prekey_ids';

  String _oneTimePreKeyIdsKey() => 'one_time_prekey_ids';

  // ---------------------------------------------------------------------------
  // IdentityKeyStore
  // ---------------------------------------------------------------------------

  /// Seeds the identity key pair and registration id (generated by the caller
  /// via the E2EE manager). No-op if already stored.
  Future<void> setIdentityKeyPair(IdentityKeyPair pair) async {
    if (await _store.read(_identityKeyPairKey) == null) {
      await _store.write(
        _identityKeyPairKey,
        base64Encode(pair.serialize()),
      );
    }
  }

  Future<void> setLocalRegistrationId(int registrationId) async {
    if (await _store.read(_registrationIdKey) == null) {
      await _store.write(_registrationIdKey, registrationId.toString());
    }
  }

  @override
  Future<IdentityKeyPair> getIdentityKeyPair() async {
    final raw = await _store.read(_identityKeyPairKey);
    if (raw == null) {
      throw StateError('Identity key pair has not been seeded');
    }
    return IdentityKeyPair.fromSerialized(base64Decode(raw));
  }

  @override
  Future<int> getLocalRegistrationId() async {
    final raw = await _store.read(_registrationIdKey);
    if (raw == null) {
      throw StateError('Registration id has not been seeded');
    }
    return int.parse(raw);
  }

  @override
  Future<bool> saveIdentity(
    SignalProtocolAddress address,
    IdentityKey? identityKey,
  ) async {
    if (identityKey == null) return false;
    await _store.write(
      _identityKeyKey(address),
      base64Encode(identityKey.serialize()),
    );
    return true;
  }

  @override
  Future<bool> isTrustedIdentity(
    SignalProtocolAddress address,
    IdentityKey? identityKey,
    Direction direction,
  ) async {
    final stored = await _store.read(_identityKeyKey(address));
    if (stored == null) {
      // Trust on first use.
      return true;
    }
    final expected = IdentityKey.fromBytes(base64Decode(stored), 0);
    return expected == identityKey;
  }

  @override
  Future<IdentityKey?> getIdentity(SignalProtocolAddress address) async {
    final stored = await _store.read(_identityKeyKey(address));
    if (stored == null) return null;
    return IdentityKey.fromBytes(base64Decode(stored), 0);
  }

  // ---------------------------------------------------------------------------
  // PreKeyStore (one-time prekeys)
  // ---------------------------------------------------------------------------

  @override
  Future<PreKeyRecord> loadPreKey(int preKeyId) async {
    final raw = await _store.read(_preKeyKey(preKeyId));
    if (raw == null) {
      throw InvalidKeyIdException(
        'PreKey id $preKeyId not found in local store',
      );
    }
    return PreKeyRecord.fromBuffer(base64Decode(raw));
  }

  @override
  Future<void> storePreKey(int preKeyId, PreKeyRecord record) async {
    await _store.write(_preKeyKey(preKeyId), base64Encode(record.serialize()));
    await _persistPreKeyId(preKeyId);
  }

  @override
  Future<bool> containsPreKey(int preKeyId) async =>
      await _store.read(_preKeyKey(preKeyId)) != null;

  @override
  Future<void> removePreKey(int preKeyId) async {
    await _store.delete(_preKeyKey(preKeyId));
    final ids = await _loadPreKeyIds();
    ids.remove(preKeyId);
    await _store.write(_oneTimePreKeyIdsKey(), ids.join(','));
  }

  Future<List<int>> getPreKeyIds() => _loadPreKeyIds();

  Future<void> _persistPreKeyId(int id) async {
    final ids = await _loadPreKeyIds();
    ids.add(id);
    await _store.write(_oneTimePreKeyIdsKey(), ids.join(','));
  }

  Future<List<int>> _loadPreKeyIds() async {
    final raw = await _store.read(_oneTimePreKeyIdsKey());
    if (raw == null || raw.isEmpty) return [];
    return raw.split(',').map(int.parse).toList();
  }

  // ---------------------------------------------------------------------------
  // SignedPreKeyStore
  // ---------------------------------------------------------------------------

  @override
  Future<SignedPreKeyRecord> loadSignedPreKey(int signedPreKeyId) async {
    final raw = await _store.read(_signedPreKeyKey(signedPreKeyId));
    if (raw == null) {
      throw InvalidKeyIdException(
        'SignedPreKey id $signedPreKeyId not found in local store',
      );
    }
    return SignedPreKeyRecord.fromSerialized(base64Decode(raw));
  }

  @override
  Future<List<SignedPreKeyRecord>> loadSignedPreKeys() async {
    final raw = await _store.read(_signedPreKeyIdsKey());
    if (raw == null || raw.isEmpty) return [];
    final records = <SignedPreKeyRecord>[];
    for (final id in raw.split(',').map(int.parse)) {
      try {
        records.add(await loadSignedPreKey(id));
      } on InvalidKeyIdException {
        // Skip stale ids.
      }
    }
    return records;
  }

  @override
  Future<void> storeSignedPreKey(
    int signedPreKeyId,
    SignedPreKeyRecord record,
  ) async {
    await _store.write(
      _signedPreKeyKey(signedPreKeyId),
      base64Encode(record.serialize()),
    );
    final raw = await _store.read(_signedPreKeyIdsKey());
    final ids = raw == null || raw.isEmpty
        ? <int>[]
        : raw.split(',').map(int.parse).toList();
    if (!ids.contains(signedPreKeyId)) {
      ids.add(signedPreKeyId);
      await _store.write(_signedPreKeyIdsKey(), ids.join(','));
    }
  }

  @override
  Future<bool> containsSignedPreKey(int signedPreKeyId) async =>
      await _store.read(_signedPreKeyKey(signedPreKeyId)) != null;

  @override
  Future<void> removeSignedPreKey(int signedPreKeyId) async {
    await _store.delete(_signedPreKeyKey(signedPreKeyId));
    final raw = await _store.read(_signedPreKeyIdsKey());
    if (raw == null || raw.isEmpty) return;
    final ids = raw.split(',').map(int.parse).where((i) => i != signedPreKeyId);
    await _store.write(_signedPreKeyIdsKey(), ids.join(','));
  }

  // ---------------------------------------------------------------------------
  // SessionStore
  // ---------------------------------------------------------------------------

  @override
  Future<SessionRecord> loadSession(SignalProtocolAddress address) async {
    final raw = await _store.read(_sessionKey(address));
    if (raw == null) {
      return SessionRecord();
    }
    return SessionRecord.fromSerialized(base64Decode(raw));
  }

  @override
  Future<List<int>> getSubDeviceSessions(String name) async {
    // 1:1 chats on a single device: the primary device is id 1. Additional
    // devices would be tracked here once multi-device is supported.
    return const [];
  }

  @override
  Future<void> storeSession(
    SignalProtocolAddress address,
    SessionRecord record,
  ) async {
    await _store.write(_sessionKey(address), base64Encode(record.serialize()));
  }

  @override
  Future<bool> containsSession(SignalProtocolAddress address) async =>
      await _store.read(_sessionKey(address)) != null;

  @override
  Future<void> deleteSession(SignalProtocolAddress address) async {
    await _store.delete(_sessionKey(address));
  }

  @override
  Future<void> deleteAllSessions(String name) async {
    // Single-device 1:1: nothing extra to enumerate beyond the addressed
    // sessions, which are deleted individually on logout.
  }
}

/// Persistent [SenderKeyStore] used for group-session sender keys, backed by the
/// same per-user [E2eeKeyValueStore] so group key state survives restarts.
class SecureSenderKeyStore implements SenderKeyStore {
  SecureSenderKeyStore(this._store);

  final E2eeKeyValueStore _store;

  String _senderKeyKey(SenderKeyName name) =>
      'sender_key:${name.groupId}:${name.sender.getName()}';

  @override
  Future<void> storeSenderKey(
    SenderKeyName senderKeyName,
    SenderKeyRecord record,
  ) async {
    await _store.write(
      _senderKeyKey(senderKeyName),
      base64Encode(record.serialize()),
    );
  }

  @override
  Future<SenderKeyRecord> loadSenderKey(SenderKeyName senderKeyName) async {
    final raw = await _store.read(_senderKeyKey(senderKeyName));
    if (raw == null || raw.isEmpty) {
      return SenderKeyRecord.fromSerialized(Uint8List(0));
    }
    return SenderKeyRecord.fromSerialized(base64Decode(raw));
  }
}
